# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pJnfNy4kHbuM4lJ9_AHCca7tT9aueCV

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""

import streamlit as st

st.set_page_config(
    page_title="Lista de Exercícios 4"
)
st.header("Projeto Final – Análise Contábil com Ajuste Econômico")
st.write("Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.")



import pandas as pd
arquivo = "https://raw.githubusercontent.com/lauraamperin/lista_exercicio4/refs/heads/main/empresas_dados.csv"
df = pd.read_csv(arquivo, sep=";")
st.dataframe(df.head(len(df)))

"""
3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

import matplotlib.pyplot as plt

df["Margem Líquida"] = df["Lucro Líquido"] / df["Receita Líquida"] * 100
df["ROA"] = df["Lucro Líquido"] / df["Ativo Total"] * 100

df_agrupada = df.groupby("Ano")[["Margem Líquida", "ROA"]].mean()

fig, ax = plt.subplots(figsize=(10, 6))
df_agrupada.plot(x='Ano', y='Margem Líquida', label='Margem Líquida (%)', ax=ax)
df_agrupada.plot(x='Ano', y='ROA', label='ROA (%)', ax=ax)

ax.set_title("Margem Líquida e ROA da Empresa por Ano")
ax.set_xlabel("Ano")
ax.set_ylabel("Percentual (%)")
ax.grid(True)

st.pyplot(fig)

"""
4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""

import ipeadatapy as ip

ip.list_series("IPCA")
ip.describe("PRECOS_IPCAG")

df2 = ip.timeseries("PRECOS_IPCAG", yearGreaterThan= 2009, yearSmallerThan= 2025)
df2.rename(columns={"YEAR": "Ano", "VALUE ((% a.a.))": "IPCA"}, inplace=True)
st.dataframe(df2)

"""
5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

df_combinada = pd.merge(df, df2, on="Ano")
df_combinada["Receita Real"] = df_combinada["Receita Líquida"] - (df_combinada["Receita Líquida"] * (df_combinada["IPCA"] / 100))
st.dataframe(df_combinada)

"""
6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)
"""

import matplotlib.pyplot as plt

df_agrupada2 = df_combinada.groupby("Ano")[["Receita Líquida", "Receita Real"]].mean().reset_index()

fig, ax = plt.subplots()
plt.figure(figsize=(10, 6))
df_agrupada2.plot(df_agrupada2["Ano"], df_agrupada2["Receita Líquida"], label='Receita Líquida', ax=ax)
df_agrupada2.plot(df_agrupada2["Ano"], df_agrupada2["Receita Real"], label='Receita Real', ax=ax)
plt.title("Receita Líquida e Receita Real da Empresa ao Longo dos Anos")
plt.ylabel("Em milhões (R$)")
plt.xlabel("Ano")
plt.legend()
plt.grid(True)
plt.show()
st.pyplot(fig)

"""
7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""
